[package]
name = "midi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.8.0"
# nannou = "0.18.1"
#macroquad = "0.3.20"
nannou = "0.18.1"
nannou_egui = "0.5.0"
rand = "0.8.5"
